---
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args:
          - --unsafe
      - id: check-toml
      - id: end-of-file-fixer
        exclude: '(\.md$|\.snap$)'
      - id: trailing-whitespace
        exclude: '(\.md$|\.snap$)'

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.13

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--config", .flake8]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          - "-rn"
          - "-sn"
          - "--rcfile=pyproject.toml"
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args:
          - "--config"
          - "pyproject.toml"
      - id: header
        name: header
        language: system
        types: [python]
        entry: python scripts/header.py
